
  frontend:
    build:
      context: ./wpma-frontend
    container_name: wpma-frontend
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - VIRTUAL_HOST=app.wpma.io
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=app.wpma.io
      - LETSENCRYPT_EMAIL=admin@yourdomain.com
    networks:
      - wpma-network
    depends_on:
      - backend
    restart: unless-stopped
